### PR TITLE
Apply Negex to Span Groups

### PR DESCRIPTION
**Pull request by casparhsws**
Adds options to apply negspacy on selected Span Groups over entities. Using the `use_spans` option will apply the same negspacy logic to all spans in specified span groups.

It uses black formatting and includes a test. 

Other
- Removed `test_bad_beharor` in the test which did not exist
- Changed some imports to package imports over relative imports to make testing easier

### CODE REVIEW

**Comment by casparhsws** [comment]
Hi, it looks like there are errors in the existing test set up for `test_scispacy_dep.py`. I assume these existed before as they are failing on my master branch. I can make them work but I am not sure if I will understand their purpose as well as you might.

**Comment by jenojp** [comment]
Hi - thanks! let me review this week

**Comment by jenojp** [comment]
Hi - fixed the errors in ```test_scispacy_dep.py```. This was due to the model becoming out of date. Do you want to rebase your fork from [jenojp:develop](https://github.com/jenojp/negspacy/tree/develop) ? 

Also, would you mind sharing a use case for inclusion in the docs?

**Comment by casparhsws** [comment]
Hi @jenojp , nice one! I will rebase, add an example and I think I will change the arguments to only have an additional `span_keys` and default it to an empty list. I can show in the example that the default spans are under key "sc". Seems simpler on second look.

**Comment by casparhsws** [comment]
@jenojp Should be ready to go after checks 👍

**Comment by jenojp** [comment]
Apologies for getting back to this so slowly! Have been finishing a big project in my day job :-) . 

Thanks again for the PR and adding to the README. I will push a release with this update.

**Comment by casparhsws** [comment]
Hey @jenojp, no problem. Happy to contribute :) Thanks for the great add on, it's been really helpful. This might help with a couple of outstanding issue/questions too, I can share my thought.

**Pull request merged**
